export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_ARTICLES = 'SET_ARTICLES',
    SET_USERS = 'SET_USERS',
    SET_MANAGERS = 'SET_MANAGERS',
    SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN',
    SET_TRANSACTIONS = 'SET_TRANSACTIONS',
    SET_ORDERS = 'SET_ORDERS',
    SET_MONEY_OUTPUT = 'SET_MONEY_OUTPUT',
    SET_UNVISITED_MONEY_OUTPUT = 'SET_UNVISITED_MONEY_OUTPUT',
    SET_UNVISITED_MESSAGE_HISTORY = 'SET_UNVISITED_MESSAGE_HISTORY';
